// platform-v2/src/lib/components/Sidebar.svelte
<script lang="ts">
  import { page } from '$app/state';
  import { auth } from '$lib/stores/auth';
  import { goto } from '$app/navigation';
  import {
    LayoutGrid,
    Rocket,
    Users,
    Wallet,
    Settings,
    LogOut,
    FileText,
    DollarSign
  } from 'lucide-svelte';

  const adminNavItems = [
    { href: '/', icon: LayoutGrid, label: 'Dashboard' },
    { href: '/ventures', icon: Rocket, label: 'Ventures' },
    { href: '/partners', icon: Users, label: 'Partners' },
    { href: '/expenses', icon: Wallet, label: 'Studio' },
    { href: '/settings', icon: Settings, label: 'Settings' }
  ];

  const partnerNavItems = [
    { href: '/', icon: LayoutGrid, label: 'My Portfolio' },
    { href: '/payouts', icon: DollarSign, label: 'Payouts' },
    { href: '/contract', icon: FileText, label: 'Contract' }
  ];

  function handleLogout() {
    auth.logout();
    goto('/login');
  }

  let navItems = $derived($auth.isAdmin ? adminNavItems : partnerNavItems);
</script>

<aside class="fixed left-0 top-0 w-[260px] h-screen bg-[#0a0a0a]/80 backdrop-blur-xl border-r border-white/[0.05] flex flex-col z-50 p-6">
  <!-- Logo -->
  <div class="px-2 mb-6">
    <div class="text-[11px] font-bold tracking-[0.3em] text-indigo-400">MINDMUSH</div>
    <div class="text-[11px] text-white/45 tracking-wide mt-1">Internal Platform</div>
  </div>

  <!-- User Badge -->
  {#if $auth.currentUser}
    <div class="flex items-center gap-3 p-3.5 bg-white/[0.025] rounded-xl border border-white/[0.05] mb-6">
      <div class="w-10 h-10 rounded-[10px] bg-gradient-to-br from-indigo-500 to-purple-500 flex items-center justify-center text-white font-semibold text-sm">
        {$auth.currentUser.username.charAt(0).toUpperCase()}
      </div>
      <div class="flex-1 min-w-0">
        <div class="text-sm font-medium text-white truncate">{$auth.currentUser.username}</div>
        <div class="text-[11px] uppercase tracking-wider mt-0.5" class:text-indigo-400={$auth.currentUser.role === 'admin'} class:text-green-400={$auth.currentUser.role === 'partner'}>
          {$auth.currentUser.role}
        </div>
      </div>
    </div>
  {/if}

  <!-- Navigation -->
  <nav class="flex-1 overflow-y-auto">
    <div class="text-[10px] font-semibold text-white/45 uppercase tracking-[0.12em] mb-2.5 px-3">
      {$auth.isAdmin ? 'Management' : 'Overview'}
    </div>

    <div class="space-y-1">
      {#each navItems as item}
        {@const isActive = page.url.pathname === item.href || (item.href !== '/' && page.url.pathname.startsWith(item.href))}
        <a
          href={item.href}
          class="flex items-center gap-3 px-3 py-3 rounded-xl text-sm font-medium transition-all duration-200 {isActive ? 'bg-gradient-to-r from-indigo-500 to-purple-500 text-white shadow-lg shadow-indigo-500/25' : 'text-white/45 hover:bg-white/5 hover:text-white'}"
        >
          <item.icon size={18} />
          {item.label}
        </a>
      {/each}
    </div>
  </nav>

  <!-- Logout -->
  <div class="pt-4 border-t border-white/[0.05] mt-auto">
    <button
      onclick={handleLogout}
      class="flex items-center gap-3 w-full px-3 py-3 rounded-xl text-sm font-medium text-white/45 hover:bg-red-500/10 hover:text-red-400 transition-all duration-200"
    >
      <LogOut size={18} />
      Sign Out
    </button>
  </div>
</aside>

// src/components/platform/Sidebar.tsx
import { motion } from 'framer-motion';
import type { User } from '../../utils/platform/types';

export type Page =
  | 'dashboard'
  | 'ventures'
  | 'ventureDetail'
  | 'partners'
  | 'expenses'
  | 'settings'
  | 'partnerDashboard'
  | 'partnerPayouts'
  | 'partnerContract'
  | 'partnerVentureDetail';

interface NavItem {
  id: Page;
  label: string;
  icon: React.ReactNode;
}

interface SidebarProps {
  user: User;
  currentPage: Page;
  onNavigate: (page: Page) => void;
  onLogout: () => void;
}

const adminNav: NavItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
      </svg>
    ),
  },
  {
    id: 'ventures',
    label: 'Ventures',
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
      </svg>
    ),
  },
  {
    id: 'partners',
    label: 'Partners',
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
      </svg>
    ),
  },
  {
    id: 'expenses',
    label: 'Studio',
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M2.25 18.75a60.07 60.07 0 0115.797 2.101c.727.198 1.453-.342 1.453-1.096V18.75M3.75 4.5v.75A.75.75 0 013 6h-.75m0 0v-.375c0-.621.504-1.125 1.125-1.125H20.25M2.25 6v9m18-10.5v.75c0 .414.336.75.75.75h.75m-1.5-1.5h.375c.621 0 1.125.504 1.125 1.125v9.75c0 .621-.504 1.125-1.125 1.125h-.375m1.5-1.5H21a.75.75 0 00-.75.75v.75m0 0H3.75m0 0h-.375a1.125 1.125 0 01-1.125-1.125V15m1.5 1.5v-.75A.75.75 0 003 15h-.75M15 10.5a3 3 0 11-6 0 3 3 0 016 0zm3 0h.008v.008H18V10.5zm-12 0h.008v.008H6V10.5z" />
      </svg>
    ),
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M10.343 3.94c.09-.542.56-.94 1.11-.94h1.093c.55 0 1.02.398 1.11.94l.149.894c.07.424.384.764.78.93.398.164.855.142 1.205-.108l.737-.527a1.125 1.125 0 011.45.12l.773.774c.39.389.44 1.002.12 1.45l-.527.737c-.25.35-.272.806-.107 1.204.165.397.505.71.93.78l.893.15c.543.09.94.56.94 1.109v1.094c0 .55-.397 1.02-.94 1.11l-.893.149c-.425.07-.765.383-.93.78-.165.398-.143.854.107 1.204l.527.738c.32.447.269 1.06-.12 1.45l-.774.773a1.125 1.125 0 01-1.449.12l-.738-.527c-.35-.25-.806-.272-1.203-.107-.397.165-.71.505-.781.929l-.149.894c-.09.542-.56.94-1.11.94h-1.094c-.55 0-1.019-.398-1.11-.94l-.148-.894c-.071-.424-.384-.764-.781-.93-.398-.164-.854-.142-1.204.108l-.738.527c-.447.32-1.06.269-1.45-.12l-.773-.774a1.125 1.125 0 01-.12-1.45l.527-.737c.25-.35.273-.806.108-1.204-.165-.397-.505-.71-.93-.78l-.894-.15c-.542-.09-.94-.56-.94-1.109v-1.094c0-.55.398-1.02.94-1.11l.894-.149c.424-.07.765-.383.93-.78.165-.398.143-.854-.107-1.204l-.527-.738a1.125 1.125 0 01.12-1.45l.773-.773a1.125 1.125 0 011.45-.12l.737.527c.35.25.807.272 1.204.107.397-.165.71-.505.78-.929l.15-.894z" />
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
      </svg>
    ),
  },
];

const partnerNav: NavItem[] = [
  {
    id: 'partnerDashboard',
    label: 'My Portfolio',
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3.75 6A2.25 2.25 0 016 3.75h2.25A2.25 2.25 0 0110.5 6v2.25a2.25 2.25 0 01-2.25 2.25H6a2.25 2.25 0 01-2.25-2.25V6zM3.75 15.75A2.25 2.25 0 016 13.5h2.25a2.25 2.25 0 012.25 2.25V18a2.25 2.25 0 01-2.25 2.25H6A2.25 2.25 0 013.75 18v-2.25zM13.5 6a2.25 2.25 0 012.25-2.25H18A2.25 2.25 0 0120.25 6v2.25A2.25 2.25 0 0118 10.5h-2.25a2.25 2.25 0 01-2.25-2.25V6zM13.5 15.75a2.25 2.25 0 012.25-2.25H18a2.25 2.25 0 012.25 2.25V18A2.25 2.25 0 0118 20.25h-2.25A2.25 2.25 0 0113.5 18v-2.25z" />
      </svg>
    ),
  },
  {
    id: 'partnerPayouts',
    label: 'Payouts',
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 6v12m-3-2.818l.879.659c1.171.879 3.07.879 4.242 0 1.172-.879 1.172-2.303 0-3.182C13.536 12.219 12.768 12 12 12c-.725 0-1.45-.22-2.003-.659-1.106-.879-1.106-2.303 0-3.182s2.9-.879 4.006 0l.415.33M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    ),
  },
  {
    id: 'partnerContract',
    label: 'Contract',
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
      </svg>
    ),
  },
];

export function Sidebar({ user, currentPage, onNavigate, onLogout }: SidebarProps) {
  const isAdmin = user.role === 'admin';
  const navItems = isAdmin ? adminNav : partnerNav;

  return (
    <aside className="w-64 h-screen bg-[#0a0a0b] border-r border-white/[0.06] flex flex-col">
      {/* Logo */}
      <div className="p-6 border-b border-white/[0.06]">
        <h1 className="text-lg font-bold text-white tracking-tight">
          Partner Platform
        </h1>
        <p className="text-white/40 text-xs mt-0.5">MINDMUSH LLC</p>
      </div>

      {/* Navigation */}
      <nav className="flex-1 py-4 px-3 space-y-1 overflow-y-auto">
        {navItems.map((item) => {
          const isActive = currentPage === item.id ||
            (item.id === 'ventures' && currentPage === 'ventureDetail') ||
            (item.id === 'partnerDashboard' && currentPage === 'partnerVentureDetail');

          return (
            <button
              key={item.id}
              onClick={() => onNavigate(item.id)}
              className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all relative ${
                isActive
                  ? 'text-white bg-white/[0.06]'
                  : 'text-white/50 hover:text-white hover:bg-white/[0.03]'
              }`}
            >
              {isActive && (
                <motion.div
                  layoutId="activeNav"
                  className="absolute inset-0 bg-white/[0.06] rounded-xl"
                  transition={{ type: 'spring', bounce: 0.15, duration: 0.4 }}
                />
              )}
              <span className="relative">{item.icon}</span>
              <span className="relative">{item.label}</span>
            </button>
          );
        })}
      </nav>

      {/* User section */}
      <div className="p-4 border-t border-white/[0.06]">
        <div className="flex items-center gap-3 mb-3">
          <div className={`w-9 h-9 rounded-xl flex items-center justify-center text-sm font-semibold ${
            isAdmin ? 'bg-purple-500/20 text-purple-400' : 'bg-blue-500/20 text-blue-400'
          }`}>
            {user.username.charAt(0).toUpperCase()}
          </div>
          <div className="flex-1 min-w-0">
            <p className="text-sm font-medium text-white truncate">{user.username}</p>
            <p className={`text-xs ${isAdmin ? 'text-purple-400' : 'text-blue-400'}`}>
              {isAdmin ? 'Admin' : 'Partner'}
            </p>
          </div>
        </div>
        <button
          onClick={onLogout}
          className="w-full flex items-center justify-center gap-2 px-3 py-2 rounded-xl text-sm text-white/50 hover:text-white hover:bg-white/[0.03] transition-all"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15m3 0l3-3m0 0l-3-3m3 3H9" />
          </svg>
          Sign out
        </button>
      </div>
    </aside>
  );
}
